//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySurvey.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SurveyDefinition
    {
        public long SurveyDefinitionID { get; set; }
        public long SurveyID { get; set; }
        public long QuestionID { get; set; }
    }
}
