BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS `UserRole` (
	`UserID`	INTEGER NOT NULL UNIQUE,
	`RoleID`	INTEGER NOT NULL,
	PRIMARY KEY(`UserID`)
);
CREATE TABLE IF NOT EXISTS `User` (
	`UserID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`UserName`	TEXT NOT NULL UNIQUE,
	`UserPassword`	TEXT
);
CREATE TABLE IF NOT EXISTS `SurveyDefinition` (
	`SurveyDefinitionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`SurveyID`	INTEGER NOT NULL,
	`QuestionID`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Survey` (
	`SurveyID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`SurveyName`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `Role` (
	`RoleID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`RoleName`	TEXT NOT NULL UNIQUE
);
CREATE TABLE IF NOT EXISTS `ResultDefinition` (
	`ResultDefinitionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`ResultID`	INTEGER NOT NULL,
	`QuestionID`	INTEGER NOT NULL,
	`ResultAnswer`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Result` (
	`ResultID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`SurveyID`	INTEGER NOT NULL,
	`ResultName`	TEXT,
	`UserID`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Question` (
	`QuestionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Question`	TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS `AttitudeDefinition` (
	`AttitudeDefinitionID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`AttitudeID`	INTEGER NOT NULL,
	`QuestionID`	INTEGER NOT NULL
);
CREATE TABLE IF NOT EXISTS `Attitude` (
	`AttitudeID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`AttitudeName`	TEXT NOT NULL UNIQUE
);
COMMIT;
