//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySurvey
{
    using System;
    using System.Collections.Generic;
    
    public partial class AttitudeDefinition
    {
        public long AttitudeDefinitionID { get; set; }
        public long AttitudeID { get; set; }
        public long QuestionID { get; set; }
    }
}
